name: Github-CI Push/PR tvb-recon

on:
  push:
  pull_request:

env:
  # secrets can be set in settings/secrets on github
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: building tvb-recon
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.9]
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - name: create new dir
        run: sudo mkdir -p /mnt/docker
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          build-mount-path: '/mnt/docker'
      - uses: actions/checkout@v3
      - name: show versions
        run: .github/show_system_versions.bash
      - name: show versions
        run: .github/show_system_versions.bash
      - name: change docker default root path
        run: |
          docker info | grep "Docker Root"
          sudo service docker stop
          sudo sed -i "s|}|,'data-root': '/mnt/docker'}|" /etc/docker/daemon.json
          sudo sed -i "s/'/\"/g" /etc/docker/daemon.json
          sudo cat /etc/docker/daemon.json
          sudo service docker start
          docker info | grep "Docker Root"
      - name: set owner variable
        run: echo "OWNER=${GITHUB_REPOSITORY%/*}" >> $GITHUB_ENV
      - name: set docker image tag
        if: github.ref != 'refs/heads/main'
        run: echo "DOCKER_IMAGE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: check disk space before image build
        run: df -h
      - name: get current image if available
        run: make pull-latest || true
      - name: build
        run: |
          make build
          make info-build
      - name: test
        run: make tests
      - name: print docker image info
        run: docker images
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: push
        run: |
          .github/dockerhub_login.bash
          make push
      - if: github.event_name == 'push' && github.ref != 'refs/heads/main'
        name: push
        run: |
          .github/dockerhub_login.bash
          make push-version
