name: Github-CI Push/PR tvb-recon

on:
  push:
  pull_request:

env:
  # secrets can be set in settings/secrets on github
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: building tvb-recon
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.9]
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          #swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          #build-mount-path: '/mnt/docker'
      - uses: actions/checkout@v3
      #- name: setup python environment
      #  uses: actions/setup-python@v4
      #  with:
      #    python-version: ${{ matrix.python }}
          # cache: "pip"
          # cache-dependency-path: "**/requirements*.txt"
      - name: show versions
        run: .github/show_system_versions.bash
      - name: show versions
        run: .github/show_system_versions.bash
      - name: change docker default root path
        run: |
          docker info | grep "Docker Root"
          sudo service docker stop 
          sudo rm -rf /etc/docker/daemon.json
          echo "{" | sudo tee -a /etc/docker/daemon.json
          echo ""data-root": $GITHUB_WORKSPACE" | sudo tee -a /etc/docker/daemon.json
          echo "}" | sudo tee -a /etc/docker/daemon.json
          sudo cat /etc/docker/daemon.json
          sudo service docker start
          docker info | grep "Docker Root"
      # - name: prune docker
      #   run: docker image prune -af
      - name: set owner variable
        run: echo "OWNER=${GITHUB_REPOSITORY%/*}" >> $GITHUB_ENV
      - name: set docker image tag
        if: github.ref != 'refs/heads/main'
        run: echo "DOCKER_IMAGE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: check disk space before image build
        run: df -h
      # - name: set dev environs
      #  run: make devenv
      # - name: get current image if available
      #  run: make pull-latest || true
      - name: build
        run: |
          make build
          make info-build
      # - name: test
      #   run: make tests
      # - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   name: push
      #   run: |
      #     .github/dockerhub_login.bash
      #     make push
      # - if: github.event_name == 'push' && github.ref != 'refs/heads/main'
      #   name: push
      #   run: |
      #     .github/dockerhub_login.bash
      #     make push-version
